djangoTest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('messaging/', include('messaging.urls')),
]

messaging/urls.py
from django.urls import path

from . import views

app_name = 'messaging'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:user_id>/', views.DetailView, name='detail'),
    path('<int:user_id>/add_friend', views.AddFriend, name='add_friend'),
    path('<int:user_id>/remove_friend', views.RemoveFriend, name='remove_friend'),
    path('create_friendship/<int:request_id>,<int:user_id>/', views.CreateFriendship, name='create_friendship'),
    path('destroy_friendship/<int:request_id>,<int:user_id>/', views.DestroyFriendship, name='destroy_friendship'),
    path('<int:user_id>/create_message', views.CreateMessage, name='create_message'),
    path('<int:user_id>/add_message', views.AddMessage, name='add_message'),
]

messaging/models.py
import datetime

from django.db import models
from django.utils import timezone

class User(models.Model):
    name = models.CharField(max_length=30)
    friends = models.ManyToManyField("User", blank=True)
    recieved_messages = models.ManyToManyField("Message", blank=True)    
    
    def __str__(self):
        return self.name

class Friendship(models.Model):
    from_user = models.ForeignKey(User, related_name='from_user', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='to_user', on_delete=models.CASCADE)
    
class Message(models.Model):
    subject_text = models.CharField(max_length=30)
    message_text = models.CharField(max_length=200)
    sender = models.ForeignKey(User, related_name='sender', on_delete=models.CASCADE)
    
    
class MessageRecipients(models.Model):
    message = models.ForeignKey(Message, related_name='message', on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name='recipient', on_delete=models.CASCADE)

messaging/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import User, Friendship, Message, MessageRecipients

class IndexView(generic.ListView):
    template_name = 'messaging/index.html'
    context_object_name = 'user_list'
    
    def get_queryset(self):
        return User.objects.all()

def  DetailView(request, user_id):
        user = User.objects.get(pk = user_id)
        sent_messages = Message.objects.filter(sender = user)
        return render(request, 'messaging/detail.html', {
            'user': user,
            'sent_messages': sent_messages,
        })
        
def AddFriend(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    
    if (user == False):
        return render(request, 'messaging/detail.html', {
            'user': user,
            'error_message': "Could not find user",
        })
    else:
        possible_friends_list = User.objects.all().exclude(pk=user_id)
        possible_friends_list
        return render(request, 'messaging/add_friend.html', {
            'user': user,
            'possible_friends_list': possible_friends_list
        })
        
def RemoveFriend(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    
    if (user == False):
        return render(request, 'messaging/detail.html', {
            'user': user,
            'error_message': "Could not find user",
        })
    else:
        friends_list = user.friends.all
        return render(request, 'messaging/remove_friend.html', {
            'user': user,
            'friends_list': friends_list
        })
    
def CreateFriendship(request, request_id, user_id):
    from_user = User.objects.get(id=user_id)
    to_user = User.objects.get(id=request_id)

    friendship, created = Friendship.objects.get_or_create(from_user=from_user, to_user=to_user)
    friendship.from_user.friends.add(friendship.to_user)
    friendship.to_user.friends.add(friendship.from_user)
    friendship.delete()
    if created:
        return render(request, 'messaging/detail.html', {
            'user': from_user,
        })
    else:
        return render(request, 'messaging/add_friend.html', {
            'user': from_user,
        })
        
def DestroyFriendship(request, request_id, user_id):
    from_user = User.objects.get(id=user_id)
    to_user = User.objects.get(id=request_id)
    from_user.friends.remove(from_user)
    to_user.friends.remove(to_user)

    return render(request, 'messaging/detail.html', {
        'user': from_user,
    })

def AddMessage(request, user_id):
    user = get_object_or_404(User, pk = user_id)
    
    if (user == False):
        return render(request, 'messaging/detail.html', {
            'user': user,
            'error_message': "Could not find user",
        })
    else:
        return render(request, 'messaging/add_message.html', {
            'user': user,
        })
        
def CreateMessage(request, user_id):
    sender = User.objects.get(id=user_id)
    subject_text = request.POST["subject_text"]
    message_text = request.POST["message_text"]
    new_message, created = Message.objects.get_or_create(subject_text=subject_text, message_text=message_text, sender=sender)
    if created:
        for recipient_id in request.POST["choice"]:
            recipient = User.objects.get(id=recipient_id)
            message_recipients = MessageRecipients.objects.get_or_create(message=new_message, recipient=recipient)
        return render(request, 'messaging/detail.html', {
            'user': sender,
        })
    else:
        return render(request, 'messaging/add_message.html', {
            'user': sender,
        })
        

    
    
    

messaging/templates/messaging/add_friend.html
<h1>{{user.name}}</h1>

<ul>
  {% for possible_friend in possible_friends_list%}
  {% if possible_friend and possible_friend is not user %}
  <li><p>{{ possible_friend.name }}</p><a  href="/messaging/create_friendship/{{possible_friend.id}},{{user.id}}/">Add Friend</a></li>
  {% endif %}
  {% endfor %}
</ul>

messaging/templates/messaging/add_message.html
<h1>Add a Message</h1>
<form action="{% url 'messaging:create_message' user.id %}" method="post">
{% csrf_token %}
{% for friend in user.friends.all %}
    <input type="checkbox" name="choice" id="friend{{ forloop.counter }}" value="{{ friend.id }}">
    <label for="friend{{ forloop.counter }}">{{ friend.name }}</label><br>
{% endfor %}
<label for="subject_text">Subject:</label>
<input type="text" name="subject_text" id="subject_text">
<label for="message_text">Message:</label>
<textarea name="message_text" rows="8" cols="80"></textarea>
<input type="submit" value="Send">
</form>

messaging/templates/messaging/detail.html
<h1>{{ user.name }}</h1>

<ul>
  {% for a_friend in user.friends.all %}
      <li>{{ a_friend.name }}</li>
  {% endfor %} 
</ul>

<ul>
  {% for recieved_message in user.recieved_messages.all %}
      <li>{{ recieved_message.subject_text }}
      <br>
      {{ recieved_message.message_text }}</li>
  {% endfor %} 
</ul>

<ul>
  {% for sent_message in sent_messages %}
      <li>{{ sent_message.subject_text }}
        <br>
      {{ sent_message.message_text }}</li>
  {% endfor %} 
</ul>
<a href="{% url 'messaging:add_friend' user.id %}">Add A Friend</a>
<a href="{% url 'messaging:remove_friend' user.id %}">Remove A Friend</a>

messaging/templates/messaging/index.html
<h1>Users</h1>
<ul>
  {% for user in user_list %}
      
      <li>{{ user.name }}</a></li>
  {% endfor %}
</ul>

messaging/templates/messaging/remove_friend.html
<h1>{{user.name}}</h1>

<ul>
  {% for possible_friend in friends_list%}
  {% if possible_friend is not user and possible_friend in user.friends.all %}
  <li><p>{{ possible_friend.name }}</p><a  href="/messaging/destroy_friendship/{{possible_friend.id}},{{user.id}}/">Remove Friend</a></li>
  {% endif %}
  {% endfor %}
</ul>